name: On Prs

on:
  workflow_dispatch:
  push:
    branches: [ 'main', 'release/*' ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    if: contains(github.event.pull_request.labels.*.name, 'auto-approve-me')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3

  test-with-local-bky-server:
    name: Test Attestation Service Examples Against Local BKY-AS Server
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read  # Required to clone repo
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          # Use the GH Actions role with limited permissions (i.e. read only access)
          # defined here https://github.com/blocky/atlantis-aws/blob/main/aws_iam_role.tf
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/BkyOidcGithubActionsBlocky
          aws-region: us-west-2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './test/go.mod'

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Fetch Recent Match ID
        run: |
          response=$(curl --fail --location \
              -H 'x-api-key: ${{ secrets.RIMBLE_API_KEY }}' \
              'https://rimbleanalytics.com/raw/csgo/completed-matches/')
          
          match_date=$(echo "$response" | jq -r '.[0].date')
          match_id=$(echo "$response" | jq -r '.[0].matchid')
          
          if [ -z "match_date" ] || [ -z "match_id" ]; then
            echo "Error: One or more response values are empty."
            echo "Response: $response"
            exit 1
          fi

          echo "RIMBLE_MATCH_DATE=${match_date}" >> "$GITHUB_ENV"
          echo "RIMBLE_MATCH_ID=${match_id}" >> "$GITHUB_ENV"

      - name: Run Tests
        env:
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          YOUR_COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          YOUR_DHL_API_KEY: ${{ secrets.DHL_API_KEY }}
          YOUR_PANDASCORE_API_KEY: ${{ secrets.PANDASCORE_API_KEY }}
          YOUR_PANDASCORE_API_ENDPOINT: ${{ secrets.PANDASCORE_API_ENDPOINT }}
          YOUR_RIMBLE_API_KEY: ${{ secrets.RIMBLE_API_KEY }}
          YOUR_RIMBLE_MATCH_DATE: ${{ env.RIMBLE_MATCH_DATE }}
          YOUR_RIMBLE_MATCH_ID: ${{ env.RIMBLE_MATCH_ID }}
        run: |
          nix-shell \
            --pure \
            --argstr asVersion "latest" \
            --argstr cVersion "latest" \
            --keep AWS_ACCESS_KEY_ID \
            --keep AWS_SECRET_ACCESS_KEY \
            --keep AWS_SESSION_TOKEN \
            --keep AWS_REGION \
            --keep GH_TOKEN \
            --keep YOUR_COINGECKO_API_KEY \
            --keep YOUR_DHL_API_KEY \
            --keep YOUR_PANDASCORE_API_KEY \
            --keep YOUR_PANDASCORE_API_ENDPOINT \
            --keep YOUR_RIMBLE_API_KEY \
            --keep YOUR_RIMBLE_MATCH_DATE \
            --keep YOUR_RIMBLE_MATCH_ID \
            --run "make test"
